### Login User
POST http://localhost:4000/api/user/
content-type: application/json

{
  "correo": "correox@correo.com",
  "pass": "1234555"
}

### Create User
POST http://localhost:4000/api/user/register
content-type: application/json

{
  "nombre": "Sebastian",
  "correo": "correox@correo.com",
  "pass": "1234555"
}

### Confirm Email
GET  http://localhost:4000/api/user/confirm-email/fgytqctrweajsrvn1vz77b


### RUTAS PROTEGIDAS 🔐 (Ingresar Dashboard)
GET  http://localhost:4000/api/user/dashboard